version: "2.4"

services:
  frontend:
    build: ./frontend
    container_name: netflix-frontend
    environment:
      - ENVIRONMENT=Testing
      - BACKEND_URL=http://backend:5002
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - devops-net

  backend:
    build: ./backend
    container_name: netflix-backend
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=login_events
      - BACKEND_PORT=5002
    ports:
      - "5002:5002"
    depends_on:
      - kafka
    networks:
      - devops-net

  consumer:
    build: ./backend
    container_name: netflix-consumer
    command: python consumer.py
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=login_events
      - KAFKA_GROUP_ID=login_consumer_group
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=logindata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pwd
    depends_on:
      - kafka
      - postgres
      - db-init
    networks:
      - devops-net

  db-init:
    build: ./backend
    container_name: netflix-db-init
    command: python db_init.py
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=logindata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pwd
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - devops-net

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: logindata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d logindata"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - devops-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - devops-net

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - devops-net

volumes:
  postgres_data:

networks:
  devops-net:
    driver: bridge
